on:
push:
    branches-ignore:
      - main
    pull_request:
      branches:
        - main

  - name: Install dependencies
    run: |
      python -m pip install --upgrade pip
      python -m pip install "${{ matrix.ansible-version }}" ansible-lint molecule molecule-docker docker pytest pytest-testinfra yamllint
      if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      if [ -f requirements_dev.txt ]; then pip install -r requirements_dev.txt; fi

jobs:
  check-dist:
    runs-on: ubuntu-latest

    steps:

      - name: Lint with yamllint
        run: |
          yamllint . --format github

      - name: Test with Molecule
        run: molecule test --all
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
