  - name: Install dependencies
    run: |
      python -m pip install --upgrade pip
      python -m pip install "${{ matrix.ansible-version }}" ansible-lint molecule molecule-docker docker flake8 flake8-bugbear flake8-docstrings flake8-import-order flake8-pylint pytest pytest-testinfra yamllint
      if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      if [ -f requirements_dev.txt ]; then pip install -r requirements_dev.txt; fi

  - name: Lint with yamllint
    run: |
      yamllint . --format github

  - name: Lint with flake8
    run: |
      # stop the build if there are Python syntax errors or undefined names
      flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
      flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  - name: Test with Molecule
    run: molecule test --all
    env:
      PY_COLORS: "1"
      ANSIBLE_FORCE_COLOR: "1"
